name = "QAOA.jl"
authors = ["Tim Bode"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
NLopt = "76087f3c-5699-56af-9a33-bf431cd00edd"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
DrWatson = "2.9.1"
julia = "1.7.2"
